### ISSUE TITLE
SVM

### ISSUE THREAD

**Issue by 1loven** [Stern1996/Bearing-Fault-Diagnosis#2]
您好，我是一个故障诊断的初学者，请问svm数据处理中说CWRU中的174.mat is an exception!!!!!单独为其写了一个判断函数是为什么，这个数据有啥特殊的地方吗。万分感谢
![image](https://user-images.githubusercontent.com/116567476/199154458-2a50e0ba-e99c-4f44-8f58-d266395e890d.png)

**Comment by Stern1996** [comment]
CWRU官方数据集里面这块有问题，之前工作忙一直没看github，官方数据集里面的命名在174跟173好像是弄混了

**Comment by Stern1996** [comment]
> 



> 您好，我是一个故障诊断的初学者，请问svm数据处理中说CWRU中的174.mat is an exception!!!!!单独为其写了一个判断函数是为什么，这个数据有啥特殊的地方吗。万分感谢 ![image](https://user-images.githubusercontent.com/116567476/199154458-2a50e0ba-e99c-4f44-8f58-d266395e890d.png)

官方数据集里面173跟174的数据集命名好像弄混了，具体你可以直接看这俩数据集里面的标签名
